Update check-dangling-trufflehog.yml

diff --git a/.github/workflows/check-dangling-trufflehog.yml b/.github/workflows/check-dangling-trufflehog.yml
--- a/.github/workflows/check-dangling-trufflehog.yml
+++ b/.github/workflows/check-dangling-trufflehog.yml
@@ -14,46 +14,46 @@ on:
 
 jobs:
   prepare:
-  runs-on: ubuntu-latest
-  outputs:
-    repo-matrix: ${{ steps.set-matrix.outputs.matrix }}
-  steps:
-    - name: Generate matrix dynamically
-    - id: set-matrix
-      env:
-        GH_TOKEN: ${{ github.token }}
-      run: |
-        ORG="${{ github.event.inputs.workingOrgs || 'axonivy-market' }}"
-        INPUT_REPOS="${{ github.event.inputs.workingRepos }}"
+    runs-on: ubuntu-latest
+    outputs:
+      repo-matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - name: Generate matrix dynamically
+        id: set-matrix
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          ORG="${{ github.event.inputs.workingOrgs || 'axonivy-market' }}"
+          INPUT_REPOS="${{ github.event.inputs.workingRepos }}"
 
-        echo "🔍 Org: $ORG"
-        echo "🔍 User Repo Input: '$INPUT_REPOS'"
+          echo "🔍 Org: $ORG"
+          echo "🔍 User Repo Input: '$INPUT_REPOS'"
 
-        if [ -n "$INPUT_REPOS" ]; then
-          echo "📌 User provided repos. Using those only."
+          if [ -n "$INPUT_REPOS" ]; then
+            echo "📌 User provided repos. Using those only."
 
-          # split user input into a JSON array
-          REPOS=$(jq -R 'split(",")' <<< "$INPUT_REPOS")
+            # split user input into a JSON array
+            REPOS=$(jq -R 'split(",")' <<< "$INPUT_REPOS")
 
-        else
-          echo "📦 No repos provided. Fetching all repos from org: $ORG"
+          else
+            echo "📦 No repos provided. Fetching all repos from org: $ORG"
 
-          REPOS=$(gh repo list "$ORG" --limit 1000 --json name -q '[.[].name]')
+            REPOS=$(gh repo list "$ORG" --limit 1000 --json name -q '[.[].name]')
 
-          if [ -z "$REPOS" ] || [ "$REPOS" = "[]" ]; then
-            echo "❌ No repos found or missing permissions"
-            exit 1
+            if [ -z "$REPOS" ] || [ "$REPOS" = "[]" ]; then
+              echo "❌ No repos found or missing permissions"
+              exit 1
+            fi
           fi
-        fi
 
-        echo "📦 Final repo list: $REPOS"
+          echo "📦 Final repo list: $REPOS"
 
-        MATRIX_JSON=$(jq -n --argjson repos "$REPOS" '{ include: $repos }')
+          MATRIX_JSON=$(jq -n --argjson repos "$REPOS" '{ include: $repos }')
 
-        # Output matrix
-        echo "matrix<<EOF" >> $GITHUB_OUTPUT
-        echo "$MATRIX_JSON" >> $GITHUB_OUTPUT
-        echo "EOF" >> $GITHUB_OUTPUT
+          # Output matrix
+          echo "matrix<<EOF" >> $GITHUB_OUTPUT
+          echo "$MATRIX_JSON" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
 
   truffle-scan:
     needs: prepare
